name: bmj-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.3.1
  - lxml=6.0.0
  - tqdm=4.67.1
  - pyyaml=6.0.2
  - openpyxl=3.0.9
  - pip
  - pip:
      - vllm==0.10.0
